[workspace]
members = [
  "zomes/p2pmessage/integrity",
  "zomes/p2pmessage/coordinator",
  "zomes/p2pmessage/types/integrity_types",
  "zomes/p2pmessage/types/coordinator_types",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
