[workspace]
members = [
  "zomes/p2pmessage",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = { git = "https://github.com/holochain/holochain", rev = "3503b38abf4196ee8b21ba09c7a4e348794ce4d4", package = "hdk", version = "0.0.106" }
