[package]
authors = ["nickolie.pangarungan@gmail.com", "tatsuya.g.sato@yumeville.com"]
description = "Integrity for p2pmessage zome"
edition = "2021"
license = "MIT"
name = "p2pmessage_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "p2pmessage_integrity"

[dependencies]
derive_more = "0"
serde = "1"

p2pmessage_integrity_types = {path = "../types/integrity_types"}
holochain_deterministic_integrity = "=0.0.10"